name: package

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: |
          mkdir dist target
          cp -r Fusion/* dist/
          rm -rf dist/Scripts/Utility/*
          rm -rf dist/Config/RCMColorSpaceMatchHotkey.fu
          cp -r Fusion/Scripts/Utility/Lua/* dist/Scripts/Utility/
          7z a target/script.zip ./dist/*
          cp Fusion/Scripts/Utility/Lua/Script\ Installer.lua target/

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*
